version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/db/:/var/lib/postgresql/data/
    networks:
      - file_handler_network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./.docker/pgadmin:/var/lib/pgadmin
    ports:
      - "8001:80"
    networks:
      - file_handler_network
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
        - ./migrations:/migrations
    command: ["-path", "./migrations", "-database",  "$DATABASE_MIGRATION_URL", "up", "1" ]
    networks:
        - file_handler_network
        
  backend:
    container_name: backend
    depends_on:
      - postgres
    env_file:
      - .env
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./uploads:/uploads
    ports:
      - "8000:8000"
    networks:
      - file_handler_network
      
networks:
  file_handler_network:
    name: file_handler_network